### ISSUE TITLE
Grössere Grössen messen

### ISSUE THREAD

**Issue by florianmuellerCH** [audacus/GroessenMesser#1]
Ich würde gerne nicht nur kleine Grössen, sondern auch grössere Grössen messen. Wie gross ist die grösste Grösse die man mit dem GroessenMesser messen kann?

**Comment by audacus** [comment]
Um grössere Grössen messen zu können, kann man die Distanz zur zu vermessenden Grösse vergrössern, somit wird es möglich auch grössere Grössen zu messen.

Die grösste Grösse die man mit dem GroessenMesser messen kann ist von der Distanz zur zu vermessenden Grösse abhängig. Der Winkel zum Ausmessen darf maximal 89° betragen. Somit kann die grösstmöglich messbare Grösse mit der Distanz zur zu vermessenden Grösse wie folgt ausgerechnet werden:

grösste Grösse = Distanz * tan(89)
